
## 플러그인 문의 : 디스코드 jooon0447 (제작자)

## 건차 생성을 허용할 월드명을 설정합니다.
건차 생성 월드 : world

## 가로 x 세로의 정사각형의 길이를 의미합니다.
건차 기본 범위 : 10

## 건차의 기본 높이를 설정합니다.
건차 기본 높이 : 20

## 건차 간의 간격을 의미합니다. 건차의 중심부를 기준으로 계산하며, 기본 범위 이상의 값을 권장합니다.
건차 간의 간격 : 30